import type { Metadata } from "next";
import { Archivo_Narrow,  Inter } from "next/font/google";
import "./globals.css";
import RootLayoutClient from "./RootLayoutClient";

const archiveNarrow = Archivo_Narrow({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zosia VanMeter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archiveNarrow.variable} ${inter.variable} h-full antialiased`}
    >
      <body><RootLayoutClient>{children}</RootLayoutClient></body>
    </html>
  );
}
